//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_CUST
    {
        public string CONTRACT_ID { get; set; }
        public string CST_CODE { get; set; }
        public string CONTRACT_CODE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string PRD_ID { get; set; }
        public string DEVICE_ID { get; set; }
        public string VALID_DATE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
